### ISSUE TITLE
Adding the module to the console config breaks the console app

### ISSUE THREAD

**Issue by mrbig00** [2amigos/yii2-usuario#206]
### What steps will reproduce the problem?
Adding the migration namespace to the console config, like described in the documentation:
```
'migrationNamespaces' => [
    'Da\User\Migration',
],
```
or adding:
```
'modules'       => [
    'class' => 'Da\User\Module',
],
```
and run ./yii
### What is the expected result?
Run yii command without errors

### What do you get instead?
```
Exception 'yii\base\InvalidArgumentException' with message 'Invalid path alias: @Da/User/controllers'

in /home/mrbig/WebProjects/thermo-control/vendor/yiisoft/yii2/BaseYii.php:154

Stack trace:
#0 /home/mrbig/WebProjects/thermo-control/vendor/yiisoft/yii2/base/Module.php(257): yii\BaseYii::getAlias('@Da/User/contro...')
#1 /home/mrbig/WebProjects/thermo-control/vendor/yiisoft/yii2/console/controllers/HelpController.php(246): yii\base\Module->getControllerPath()
#2 /home/mrbig/WebProjects/thermo-control/vendor/yiisoft/yii2/console/controllers/HelpController.php(241): yii\console\controllers\HelpController->getModuleCommands(Object(Da\User\Module))
#3 /home/mrbig/WebProjects/thermo-control/vendor/yiisoft/yii2/console/controllers/HelpController.php(175): yii\console\controllers\HelpController->getModuleCommands(Object(yii\console\Application))
#4 /home/mrbig/WebProjects/thermo-control/vendor/yiisoft/yii2/console/controllers/HelpController.php(187): yii\console\controllers\HelpController->getCommands()
#5 /home/mrbig/WebProjects/thermo-control/vendor/yiisoft/yii2/console/controllers/HelpController.php(293): yii\console\controllers\HelpController->getCommandDescriptions()
#6 /home/mrbig/WebProjects/thermo-control/vendor/yiisoft/yii2/console/controllers/HelpController.php(67): yii\console\controllers\HelpController->getDefaultHelp()
#7 [internal function]: yii\console\controllers\HelpController->actionIndex(NULL)
#8 /home/mrbig/WebProjects/thermo-control/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /home/mrbig/WebProjects/thermo-control/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#10 /home/mrbig/WebProjects/thermo-control/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('', Array)
#11 /home/mrbig/WebProjects/thermo-control/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('', Array)
#12 /home/mrbig/WebProjects/thermo-control/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('', Array)
#13 /home/mrbig/WebProjects/thermo-control/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('', Array)
#14 /home/mrbig/WebProjects/thermo-control/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#15 /home/mrbig/WebProjects/thermo-control/bin/yii(20): yii\base\Application->run()
#16 {main}

```

Edits: made multiple tests & stuff

**Comment by tonydspaniard** [comment]
This is mine and works: 

```php 
 'controllerMap' => [
        'migrate' => [
            'class' => \yii\console\controllers\MigrateController::class,
            'migrationPath' => [
                '@app/migrations',
                '@yii/rbac/migrations', // Just in case you forgot to run it on console (see next note)
            ],
            'migrationNamespaces' => [
                'Da\User\Migration',
            ],
        ],
    ],

**Comment by mrbig00** [comment]
The `'class' => Da\User\Module::class` and `'class' => 'Da\User\Module'` should do the same, no?

**Comment by tonydspaniard** [comment]
@mrbig00 nope... should be: 

```php 
'modules'       => [
    [
       'class' => 'Da\User\Module',
    ]
],
```

not 
```php 
'modules'       => [
       'class' => 'Da\User\Module',
],
```

Also, I highly recommend you to name your modules (i.e. 'gii' => [], 'user' => [])

**Comment by mrbig00** [comment]
Oh, I'm dumb. I should take out a vacation or smth.

**Comment by mrbig00** [comment]
Please close this issue
