### ISSUE TITLE
Creating admin user with Yii2-migration

### ISSUE THREAD

**Issue by WeeSee** [2amigos/yii2-usuario#295]
### What steps will reproduce the problem?

Migration should create admin user without email for confirmation.

` ./yii migrate/up `

The migration class (the `$mailService` is required but should not be used):

```
    use ContainerAwareTrait;

    public function safeUp()
    {
        $user = $this->make(User::class,[],[
            'scenario' => 'create', 
            'email' => 'admin@example.com',
            'username' => 'admin',
            'password' => 'admin',
        ]);
        $mailService = MailFactory::makeWelcomeMailerService($user);
        if (!$this->make(UserCreateService::class, [$user, $mailService])->run()
            || $this->assignRole($user, $role)
            || $this->make(UserConfirmationService::class, [$user])->run()
        ) {
            $this->stdout("Fehler: Benutzer admin konnte nicht angelegt werden!\n", 
                Console::FG_RED);
            return false;
        }
    }
```

### What is the expected result?

User admin created.

### What do you get instead?

I get a stack trace:

```
Exception: Trying to get property 'mailParams' of non-object (/app/vendor/2amigos/yii2-usuario/src/User/Factory/MailFactory.php:36)
#0 /app/vendor/2amigos/yii2-usuario/src/User/Factory/MailFactory.php(36): yii\base\ErrorHandler->handleError(8, 'Trying to get p...', '/app/vendor/2am...', 36, Array)
#1 /app/migrations/m181201_160037_useradmin.php(23): Da\User\Factory\MailFactory::makeWelcomeMailerService(Object(Da\User\Model\User))
#2 /app/vendor/yiisoft/yii2/db/Migration.php(114): m181201_160037_useradmin->safeUp()
#3 /app/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(725): yii\db\Migration->up()
#4 /app/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(199): yii\console\controllers\BaseMigrateController->migrateUp('m181201_160037_...')
#5 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#6 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#7 /app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#8 /app/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('up', Array)
#9 /app/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('up', Array)
#10 /app/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/up', Array)
#11 /app/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('migrate/up', Array)
#12 /app/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#13 /app/yii(20): yii\base\Application->run()
#14 {main}

```

**Comment by tonydspaniard** [comment]
That command is to facilitate the creation of users not admins. I personally have created two console commands for that: 

- One that creates the roles 
- Another one that creates users by roles (without confirmations required) 

I recommend you to do the same.

**Comment by mtangoo** [comment]
If not tied to your project details then it will make a good addition to the already comprehensive Docs!

**Comment by tonydspaniard** [comment]
The above issue is due that the module is not configured on console app.
