### ISSUE TITLE
'Object configuration must be an array containing a "class" or "__class" element.'

### ISSUE THREAD

**Issue by LarryTX** [2amigos/yii2-usuario#363]
### What steps will reproduce the problem?

1. Install yii2-usuario via `composer require 2amigos/yii2-usuario:~1.0`. Also tried `composer require 2amigos/yii2-usuario: 'dev-master'` to see if it would make a difference with dev-master; no difference.

1. Modify `%PROJECT_DIR%/console/config/main.php` to read as follows:
```php
    'controllerMap' => [
                'fixture' => [
                    'class'     => 'yii\console\controllers\FixtureController',
                    'namespace' => 'common\fixtures',
                ],
                'migrate' => [
                    'class'               => 'yii\console\controllers\MigrateController',
                    'migrationPath'       => [
                        '@app/migrations',
                        '@yii/rbac/migrations',
                    ],
                    'migrationNamespaces' => [
                        'Da\User\Migration',
                    ],
                ],
            ],
```

3. Attempt to run the migrations via `yii migrate`.

### What is the expected result?
rbac and usario migrations run to produce required tables.
### What do you get instead?
Error message stating:
```
Exception 'yii\base\InvalidConfigException' with message 'Object configuration must be an array containing a "class" or "__class" element.'
```
### **Comments**
First, I have attempted to find a solution for this ubiquitous problem. Nothing I've fond seems to work or be relevant. Hope someone can help.

This seems to be an upgrade-related issue because it worked just fine on another website on a previous version of Yii2. For what it's worth, here's the stats:

- **Yii2 version**: 2.0.30

- **PHP version**:  7.3.11

- **yii2-usuario version**: 1.1.4 (also, independently tried dev-master)

- **Catabase**: PostgreSQL 12.1.1

Any help will be most appreciated. If I can find a way to work around the migration problems, I can create the tables using the migrations as a model. However, I feel like I will likely encounter this same issue elsewhere.

**Comment by maxxer** [comment]
Config appears correct. The only option which comes to my mind is the presence of some weird character in the text, like in the `class` line or something like that. Try retyping the whole row in a new line from scratch

**Comment by LarryTX** [comment]
Thanks, @maxxer , but it gets even worse. I got to thinking, What if the problem is in the rbac migration since this approach would involve it as well. (I only wish the Yii2 stack trace would pinpoint the actual source of the error instead of pointing back to core modules which is almost always totally useless information.) So I commented out the rbac migration in migrationpath. Same error. Then, I tried the reverse with usuario commented out and rbac uncommented. Same error. Then I commented out all the migrationPath and migrationNamespaces and tried running `yii migrate --migrationPath=@yii/rbac/migrations`. Same error. Also, same error with `yii migrate --migrationNamespaces=Da\\User\\Migration`.

As I suspected, that pretty much rules out **yii2-usuario** as being at the root of the problem and brings me back to my original suspicion — the Yii2 2.0.30 upgrade — especially since I never had this problem with usuario before. (All my previous problems had been of my own making.)

Now I'm inclined to downgrade Yii2 and see if a previous version works. I just have to figure out what version to go to.

**Comment by maxxer** [comment]
Please let me know how it works.

**Comment by maxxer** [comment]
I just tried creating a new project with Yii 2.0.32 and usuario dev-master and migrations went fine. But I'm on MySQL.

**Comment by amlopezalonso** [comment]
I ran into this same issue (using MySQL) when attempting to migrate from a previous Dektrium installation following the steps detailed in:

[https://yii2-usuario.readthedocs.io/en/latest/installation/migration-guide-from-dektrium-tools/](url)

As soon as I tried to apply the first proposed migration:

`./yii migrate/mark "Da\User\Migration\m000000_000005_add_last_login_at" `

I got:

> Exception 'yii\base\InvalidConfigException' with message 'Object configuration must be an array containing a "class" or "__class" element.'
in /usr/local/share/datos/tmp/desarrollo/tarha/vendor/yiisoft/yii2/BaseYii.php:368
Stack trace:
#0 /usr/local/share/datos/tmp/desarrollo/tarha/vendor/yiisoft/yii2/base/Module.php(427): yii\BaseYii::createObject(Array, Array)
#1 /usr/local/share/datos/tmp/desarrollo/tarha/vendor/2amigos/yii2-usuario/src/User/Bootstrap.php(44): yii\base\Module->getModule('user')
#2 /usr/local/share/datos/tmp/desarrollo/tarha/vendor/yiisoft/yii2/base/Application.php(297): Da\User\Bootstrap->bootstrap(Object(yii\console\Application))
#3 /usr/local/share/datos/tmp/desarrollo/tarha/vendor/yiisoft/yii2/base/Application.php(273): yii\base\Application->bootstrap()
#4 /usr/local/share/datos/tmp/desarrollo/tarha/vendor/yiisoft/yii2/console/Application.php(124): yii\base\Application->init()
#5 /usr/local/share/datos/tmp/desarrollo/tarha/vendor/yiisoft/yii2/base/BaseObject.php(109): yii\console\Application->init()
#6 /usr/local/share/datos/tmp/desarrollo/tarha/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#7 /usr/local/share/datos/tmp/desarrollo/tarha/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
#8 /usr/local/share/datos/tmp/desarrollo/tarha/yii(22): yii\console\Application->__construct(Array)
#9 {main}

Trying to reach the site:

> yii\base\UnknownPropertyException: Setting unknown property: Da\User\Module::admins in /usr/local/share/datos/tmp/desarrollo/tarha/vendor/yiisoft/yii2/base/Component.php:209
Stack trace:
#0 /usr/local/share/datos/tmp/desarrollo/tarha/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set('admins', Array)
#1 /usr/local/share/datos/tmp/desarrollo/tarha/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(Da\User\Module), Array)
#2 /usr/local/share/datos/tmp/desarrollo/tarha/vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject->__construct(Array)
#3 [internal function]: yii\base\Module->__construct('user', Object(yii\web\Application), Array)
#4 /usr/local/share/datos/tmp/desarrollo/tarha/vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs(Array)
#5 /usr/local/share/datos/tmp/desarrollo/tarha/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('Da\\User\\Module', Array, Array)
#6 /usr/local/share/datos/tmp/desarrollo/tarha/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('Da\\User\\Module', Array, Array)
#7 /usr/local/share/datos/tmp/desarrollo/tarha/vendor/yiisoft/yii2/base/Module.php(427): yii\BaseYii::createObject(Array, Array)
#8 /usr/local/share/datos/tmp/desarrollo/tarha/vendor/2amigos/yii2-usuario/src/User/Bootstrap.php(44): yii\base\Module->getModule('user')
#9 /usr/local/share/datos/tmp/desarrollo/tarha/vendor/yiisoft/yii2/base/Application.php(297): Da\User\Bootstrap->bootstrap(Object(yii\web\Application))
#10 /usr/local/share/datos/tmp/desarrollo/tarha/vendor/yiisoft/yii2/web/Application.php(69): yii\base\Application->bootstrap()
#11 /usr/local/share/datos/tmp/desarrollo/tarha/vendor/yiisoft/yii2/base/Application.php(273): yii\web\Application->bootstrap()
#12 /usr/local/share/datos/tmp/desarrollo/tarha/vendor/yiisoft/yii2/base/BaseObject.php(109): yii\base\Application->init()
#13 /usr/local/share/datos/tmp/desarrollo/tarha/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#14 /usr/local/share/datos/tmp/desarrollo/tarha/web/index.php(11): yii\base\Application->__construct(Array)
#15 {main}

**Comment by maxxer** [comment]
> As soon as I tried to apply the first proposed migration:

Can you post the application component and module configuration? It seems Yii is unable to fetch the module with `id => user`

**Comment by amlopezalonso** [comment]
There you are:

Components:

       /* 'user' => [ // Disabled for Dektrium / yii2-usuario.
            'identityClass' => 'app\models\User',
            'enableAutoLogin' => true,
        ],*/
        'authManager' => [
             'class' => 'yii\rbac\DbManager',
             'defaultRoles' => ['myDefaultRole'],
        ],
        'view' => [
             'theme' => [
                 'pathMap' => [
                     '@Da/User/resources/views' => '@app/views/user',
                 ],
             ],
         ],
        'db' => require(__DIR__ . '/db.php'),
    ],

Modules:

    'user' => [
              'class' => Da\User\Module::class,
              'administrators'             => ['myadmin'],
              'allowUnconfirmedEmailLogin' => false,
              'enableRegistration'         => false,
              'enableEmailConfirmation'    => true,
              'allowPasswordRecovery'      => true,
              'mailParams' => [
                'fromEmail' => 'info@mydomain',
              ],
              'classMap' => [
                'LoginForm' => 'app\models\LoginForm',
              ],
        ],
