### ISSUE TITLE
2FA qrCode implementation incompatible with >= php8.1

### ISSUE THREAD

**Issue by TonisOrmisson** [2amigos/yii2-usuario#501]
### What steps will reproduce the problem?
Run module on php8.1+. Try to enable 2fa.  

### What is the expected result?
see a modal with qr-code

### What do you get instead?
empty modal

in backround an exception is thrown:
```
2023-01-10 16:59:19 [172.18.0.1][1][g2206m7tlih6nv9g7b062lkfvr][error][yii\base\ErrorException:8192] yii\base\ErrorException: Implicit conversion from float 33.333333333333336 to int loses precision in /var/www/html/vendor/bacon/bacon-qr-code/src/BaconQrCode/Encoder/MaskUtil.php:223
Stack trace:
#0 /var/www/html/vendor/bacon/bacon-qr-code/src/BaconQrCode/Encoder/MaskUtil.php(223): yii\base\ErrorHandler->handleError(8192, 'Implicit conver...', '/var/www/html/v...', 223)        
#1 /var/www/html/vendor/bacon/bacon-qr-code/src/BaconQrCode/Encoder/MatrixUtil.php(560): BaconQrCode\Encoder\MaskUtil::getDataMaskBit(4, 40, 40)
#2 /var/www/html/vendor/bacon/bacon-qr-code/src/BaconQrCode/Encoder/MatrixUtil.php(174): BaconQrCode\Encoder\MatrixUtil::embedDataBits(Object(BaconQrCode\Common\BitArray), 4, Object(BaconQrCode\Encoder\ByteMatrix))
#3 /var/www/html/vendor/bacon/bacon-qr-code/src/BaconQrCode/Encoder/Encoder.php(234): BaconQrCode\Encoder\MatrixUtil::buildMatrix(Object(BaconQrCode\Common\BitArray), Object(BaconQrCode\Common\ErrorCorrectionLevel), Object(BaconQrCode\Common\Version), 4, Object(BaconQrCode\Encoder\ByteMatrix))
#4 /var/www/html/vendor/bacon/bacon-qr-code/src/BaconQrCode/Encoder/Encoder.php(134): BaconQrCode\Encoder\Encoder::chooseMaskPattern(Object(BaconQrCode\Common\BitArray), Object(BaconQrCode\Common\ErrorCorrectionLevel), Object(BaconQrCode\Common\Version), Object(BaconQrCode\Encoder\ByteMatrix))
#5 /var/www/html/vendor/bacon/bacon-qr-code/src/BaconQrCode/Writer.php(82): BaconQrCode\Encoder\Encoder::encode('otpauth://totp/...', Object(BaconQrCode\Common\ErrorCorrectionLevel), 'UTF-8')
#6 /var/www/html/vendor/2amigos/qrcode-library/src/Traits/ImageTrait.php(60): BaconQrCode\Writer->writeString('otpauth://totp/...', 'UTF-8', '0')
#7 /var/www/html/vendor/2amigos/qrcode-library/src/Writer/AbstractWriter.php(43): Da\QrCode\Writer\PngWriter->writeString(Object(Da\QrCode\QrCode))
#8 /var/www/html/vendor/2amigos/qrcode-library/src/QrCode.php(342): Da\QrCode\Writer\AbstractWriter->writeDataUri(Object(Da\QrCode\QrCode))
#9 /var/www/html/vendor/2amigos/2fa-library/src/Service/QrCodeDataUriGeneratorService.php(48): Da\QrCode\QrCode->writeDataUri()
#10 /var/www/html/modules/usuario/src/User/Service/TwoFactorQrCodeUriGeneratorService.php(51): Da\TwoFA\Service\QrCodeDataUriGeneratorService->run()
#11 /var/www/html/modules/usuario/src/User/Controller/SettingsController.php(475): Da\User\Service\TwoFactorQrCodeUriGeneratorService->run()
#12 [internal function]: Da\User\Controller\SettingsController->actionTwoFactor('1')
#13 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#15 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('two-factor', Array)
#16 /var/www/html/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('user/settings/t...', Array)
#17 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#18 /var/www/html/web/index.php(12): yii\base\Application->run()

```

bacon/bacon-qr-code ir required by 2amigos/qrcode-library which is required by 2amigos/2fa-library
No update version seem to be available. Both libs from 2amigos seem to be not very active :(

**Comment by maxxer** [comment]
@tonydspaniard can you grant us write access to those repos? 🙏
