### ISSUE TITLE
InvalidConfigException when trying to run Yii console script after migrating to yii2-usuario

### ISSUE THREAD

**Issue by amlopezalonso** [2amigos/yii2-usuario#510]
### What steps will reproduce the problem?
Try to run the ./yii script with any options or no options at all.

### What is the expected result?
Any proper result from the yii script

### What do you get instead?
The following error / trace:

```
Exception 'yii\base\InvalidConfigException' with message 'Object configuration must be an array containing a "class" or "__class" element.'

in /myapp/vendor/yiisoft/yii2/BaseYii.php:368

Stack trace:
#0 /myapp/vendor/yiisoft/yii2/base/Module.php(445): yii\BaseYii::createObject()
#1 /myapp/vendor/2amigos/yii2-usuario/src/User/Bootstrap.php(47): yii\base\Module->getModule()
#2 /myapp/vendor/yiisoft/yii2/base/Application.php(295): Da\User\Bootstrap->bootstrap()
#3 /myapp/vendor/yiisoft/yii2/base/Application.php(271): yii\base\Application->bootstrap()
#4 /myapp/vendor/yiisoft/yii2/console/Application.php(124): yii\base\Application->init()
#5 /myapp/vendor/yiisoft/yii2/base/BaseObject.php(109): yii\console\Application->init()
#6 /myapp/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct()
#7 /myapp/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct()
#8 /myapp/yii(22): yii\console\Application->__construct()
#9 {main}
```
Got this in `web/config.php` (basic template app):

```
<?php

// Yii::setAlias('@tests', dirname(__DIR__) . '/tests');

$params = require(__DIR__ . '/params.php');
$db = require(__DIR__ . '/db.php');

return [
    'id' => 'basic-console',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log', 'gii'],
    'controllerNamespace' => 'app\commands',
    'aliases' => [
        '@bower' => '@vendor/bower-asset',
        '@npm'   => '@vendor/npm-asset',
        '@tests' => '@app/tests',
    ],
    'controllerMap' => [
       'migrate' => [
            'class' => \yii\console\controllers\MigrateController::class,
            'migrationPath' => [
                '@app/migrations',
                '@yii/rbac/migrations',
            ],
            'migrationNamespaces' => [
                    'Da\User\Migration',
            ],
        ],
    ],
    'modules' => [
        'gii' => 'yii\gii\Module',
        'user' => [
                'user' => Da\User\Module::class,
        ],
    ],
    'components' => [
        'cache' => [
            'class' => 'yii\caching\FileCache',
        ],
        'log' => [
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'authManager' => [
//              'class' => '\dektrium\rbac\components\DbManager',
             'class' => 'yii\rbac\DbManager',
        ],
        'db' => $db,
    ],
    'params' => $params,
];
```

**Comment by maxxer** [comment]
Console commands loads configuration from `config/console.php`, did you configure it? If so, can you post it?

**Comment by TonisOrmisson** [comment]
the error message says exactly what you have wrong there
![image](https://user-images.githubusercontent.com/6357451/229045169-80df636d-2b83-476d-801c-23090133187f.png)
needs to be "class"

**Comment by amlopezalonso** [comment]
Oh my! @TonisOrmisson you are completely right... Guess I'm getting really older. Thanks for pointing that out!

Antonio
